### ISSUE TITLE
The first character is always the same in the same session

### ISSUE THREAD

**Issue by narze** [stulzer/cuid2#1]
![image](https://github.com/stulzer/cuid2/assets/248741/1257d725-cd04-4006-9688-423a867388fe)

It is caused by `#random_letter` method that is memoized

**Comment by narze** [comment]
Maybe this helps. I reimplemented from scratch with help from ChatGPT https://gist.github.com/narze/985712e46d33be3613e395388b549c2d

**Comment by stulzer** [comment]
Thanks for the report, this is fixed on #2
