### ISSUE TITLE
[Question]  Why not `.sample`?

### ISSUE THREAD

**Issue by mcampbell** [stulzer/cuid2#3]
Asking so I'm less ignorant, not a criticism.

I notice in a couple places picking a random value is done with the `values[rand(values.size).floor]` type pattern, rather than using `Array#sample`.  Is there a reason for this I'm not seeing?  Some cryptographic/mathematic property?  

"Just because" is a perfectly fine answer, was just curious.

**Comment by stulzer** [comment]
That's a good question, was just because. Pretty sure it could work with sample method. Glad to accept a PR for it too.

**Comment by mcampbell** [comment]
> That's a good question, was just because. Pretty sure it could work with sample method. Glad to accept a PR for it too.

https://github.com/stulzer/cuid2/pull/4
